"use client";

import { DailyData } from "@/lib/types";

interface Props {
  dailyData: DailyData[];
  weekLabel: string;
  clientName: string;
}

function Badge({ value, color }: { value: string | number; color: string }) {
  return (
    <span className={`inline-flex items-center justify-center min-w-[2rem] px-2.5 py-0.5 rounded-full text-xs font-semibold text-white ${color}`}>
      {value}
    </span>
  );
}

export default function BreakdownTable({ dailyData, weekLabel, clientName }: Props) {
  const totals = dailyData.reduce(
    (acc, d) => ({
      total: acc.total + d.total,
      bot: acc.bot + d.bot,
      human: acc.human + d.human,
      humanResolved: acc.humanResolved + d.humanResolved,
    }),
    { total: 0, bot: 0, human: 0, humanResolved: 0 }
  );
  const totalBotRate = totals.total > 0 ? Math.round((totals.bot / totals.total) * 100) : 0;

  return (
    <div className="bg-white rounded-xl border border-gray-100 shadow-sm overflow-hidden">
      <div className="overflow-x-auto">
        <table className="w-full">
          <thead>
            <tr className="bg-gray-50 border-b border-gray-100">
              <th className="text-left text-[11px] font-semibold tracking-widest text-gray-400 uppercase px-6 py-3">Date</th>
              <th className="text-left text-[11px] font-semibold tracking-widest text-gray-400 uppercase px-4 py-3">Total</th>
              <th className="text-left text-[11px] font-semibold tracking-widest text-gray-400 uppercase px-4 py-3">Bot Resolved</th>
              <th className="text-left text-[11px] font-semibold tracking-widest text-gray-400 uppercase px-4 py-3">Human Handled</th>
              <th className="text-left text-[11px] font-semibold tracking-widest text-gray-400 uppercase px-4 py-3">Human Resolved</th>
              <th className="text-left text-[11px] font-semibold tracking-widest text-gray-400 uppercase px-4 py-3">Bot Rate</th>
            </tr>
          </thead>
          <tbody>
            {dailyData.map((d, i) => (
              <tr key={i} className="border-t border-gray-50 hover:bg-gray-50/50 transition-colors">
                <td className="px-6 py-3 font-semibold text-sm text-gray-800">{d.date}</td>
                <td className="px-4 py-3 text-sm text-gray-700">{d.total}</td>
                <td className="px-4 py-3"><Badge value={d.bot} color="bg-green-500" /></td>
                <td className="px-4 py-3"><Badge value={d.human} color="bg-amber-400" /></td>
                <td className="px-4 py-3"><Badge value={d.humanResolved} color="bg-blue-400" /></td>
                <td className="px-4 py-3">
                  <Badge
                    value={`${Math.round(d.botRate)}%`}
                    color={d.botRate >= 70 ? "bg-green-500" : d.botRate >= 50 ? "bg-amber-400" : "bg-red-400"}
                  />
                </td>
              </tr>
            ))}
            {/* Totals row */}
            <tr className="border-t-2 border-gray-200 bg-gray-50">
              <td className="px-6 py-3 font-bold text-sm text-gray-800">TOTAL</td>
              <td className="px-4 py-3 font-bold text-sm text-gray-800">{totals.total}</td>
              <td className="px-4 py-3"><Badge value={totals.bot} color="bg-green-500" /></td>
              <td className="px-4 py-3"><Badge value={totals.human} color="bg-amber-400" /></td>
              <td className="px-4 py-3"><Badge value={totals.humanResolved} color="bg-blue-400" /></td>
              <td className="px-4 py-3"><Badge value={`${totalBotRate}%`} color="bg-green-500" /></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div className="px-6 py-3 border-t border-gray-100">
        <p className="text-center text-xs text-gray-400">
          Generated by Claude Code · {clientName} Chatbot Analytics · Source: Chatwoot API · As of {dailyData[dailyData.length - 1]?.date}
        </p>
      </div>
    </div>
  );
}
